source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PGLContacts_Example', :exclusive => true do
  pod "PGLContacts", :path => "../"
end

target 'PGLContacts_Tests', :exclusive => true do
  pod "PGLContacts", :path => "../"

  
end
